- name: main | add vars
  include_vars: "{{ ansible_os_family }}.yml"

- include: php.yml

- name: main | check version
  shell: "php -i | grep 'PHP Version' | head -1 | sed -r 's/^.{15}//'"
  register: php_version

- name: main | set facts
  set_fact:
    php_version_53: "{{ 'yes' if '5.3.' in php_version.stdout else 'no' }}"
    php_version_54: "{{ 'yes' if '5.4.' in php_version.stdout else 'no' }}"
    php_version_55: "{{ 'yes' if '5.5.' in php_version.stdout else 'no' }}"

- include: ini.yml

- include: mysql.yml
  when: mysql is defined and mysql.install == 1

- include: mariadb.yml
  when: mariadb is defined and mariadb.install == 1

- include: apache.yml
  when: apache is defined and apache.install == 1

- include: nginx.yml
  when: nginx is defined and nginx.install == 1

- include: pear.yml
  when: php_pear is defined and php__install == 1

- include: pecl.yml
  when: php_pecl is defined and php_pecl_install == 1

- include: apc.yml
  when: php_apc is defined and php_apc_install == 1

- include: composer.yml
  when: php_composer is defined and php_composer_install == 1

- include: phpmyadmin.yml
  when: php_phpmyadmin is defined and php_phpmyadmin.install == 1

- include: mailcatcher.yml
  when: php_mailcatcher is defined and php_mailcatcher_install == 1

- include: xdebug.yml
  when: php_xdebug is defined and php_xdebug_install == 1

- include: xhprof.yml
  when: php_xhprof is defined and php_xhprof_install == 1
