# Compatibility

- name: pecl | require pear
  fail: msg="PHP - Pear is required"
  when: php_pear is not defined or php_pear_install != 1

#- name: pecl | install pecl
#  command: pecl install pecl_http

# PECL Packages 

- name: pecl | install packages
  command: pecl install {{ item }}
  with_items: php_pecl_modules
  when: php_pecl_modules is defined
  ignore_errors: True
